(function registerViews(global) {
    "use strict";

    const App = global.BScan;
    const { escapeHtml, formatDate, formatNumber, initials } = App.utils;

    const icon = (name) => `<i class="fa-solid fa-${name}" aria-hidden="true"></i>`;
    const statusMap = {
        submitted: ["Отправлена", "status-submitted"], review: ["На проверке", "status-review"],
        approved: ["Подтверждена", "status-approved"], rejected: ["Отклонена", "status-rejected"]
    };

    function logo() { return `<a class="brand" href="#/dashboard" aria-label="B-scan — главная"><span class="brand-mark">${icon("sparkles")}</span><span class="brand-wordmark">B-scan</span></a>`; }
    function field(label, id, type, options = {}) {
        const attrs = [`id="${id}"`, `name="${id}"`, `type="${type}"`, options.required === false ? "" : "required", options.autocomplete ? `autocomplete="${options.autocomplete}"` : "", options.placeholder ? `placeholder="${escapeHtml(options.placeholder)}"` : "", options.minlength ? `minlength="${options.minlength}"` : ""].filter(Boolean).join(" ");
        return `<label class="field"><span>${label}</span><div class="input-wrap">${options.icon ? icon(options.icon) : ""}<input ${attrs}></div><small class="field-error" data-error-for="${id}"></small></label>`;
    }
    function authLayout(content, sideTitle = "Списания без лишней рутины") {
        return `<div class="auth-layout"><aside class="auth-visual"><div>${logo()}<div class="auth-promise"><span class="eyebrow">AI-powered operations</span><h1>${sideTitle}</h1><p>Фото, анализ и заявка — в одном понятном потоке.</p><div class="trust-row"><span>${icon("shield-halved")} Защищено</span><span>${icon("bolt")} Быстро</span><span>${icon("wand-magic-sparkles")} С AI</span></div></div></div><p class="auth-version">B-scan 2.0 • Рабочее место отправителя</p></aside><main class="auth-main" id="main-content"><div class="mobile-auth-brand">${logo()}</div>${content}</main></div>`;
    }

    function login(role = "sender") {
        const reviewer = role === "reviewer";
        return authLayout(`<section class="auth-card"><span class="eyebrow">Добро пожаловать</span><h2>${reviewer ? "Вход для проверяющих" : "Вход для отправителей"}</h2><p class="auth-subtitle">${reviewer ? "Используйте личный пароль и секретный код проверяющего." : "Войдите, чтобы продолжить работу."}</p><div class="auth-segments" role="tablist" aria-label="Тип аккаунта"><button class="${!reviewer ? "active" : ""}" type="button" data-login-role="sender" role="tab" aria-selected="${!reviewer}">${icon("user")} Отправитель</button><button class="${reviewer ? "active" : ""}" type="button" data-login-role="reviewer" role="tab" aria-selected="${reviewer}">${icon("user-shield")} Проверяющий</button></div><form id="login-form" class="form-stack" novalidate>${field("Email", "email", "email", { icon: "envelope", autocomplete: "email", placeholder: "name@restaurant.kz" })}${field("Пароль", "password", "password", { icon: "lock", autocomplete: "current-password", placeholder: "Ваш пароль" })}<div class="manager-secret-field ${reviewer ? "visible" : ""}" aria-hidden="${!reviewer}">${field("Секретный код проверяющего", "managerSecretCode", "password", { icon: "key", autocomplete: "off", placeholder: "Введите секретный код", required: reviewer })}</div><div class="form-between"><label class="check"><input id="remember" type="checkbox" checked><span>Запомнить меня</span></label><a href="#/forgot">Забыли пароль?</a></div><button class="btn btn-primary btn-block" type="submit"><span>Войти</span>${icon("arrow-right")}</button></form><p class="auth-switch">Нет аккаунта? <a href="#/register">Зарегистрироваться</a></p></section>`);
    }
    function forgot() { return authLayout(`<section class="auth-card"><a class="back-link" href="#/login">${icon("arrow-left")} Назад</a><div class="auth-icon">${icon("key")}</div><h2>Восстановить пароль</h2><p class="auth-subtitle">Мы создадим одноразовый код восстановления.</p><form id="forgot-form" class="form-stack" novalidate>${field("Email", "email", "email", { icon: "envelope", autocomplete: "email" })}<button class="btn btn-primary btn-block" type="submit">Получить код</button></form></section>`); }
    function reset(token = "") { return authLayout(`<section class="auth-card"><a class="back-link" href="#/login">${icon("arrow-left")} Ко входу</a><div class="auth-icon">${icon("shield-halved")}</div><h2>Новый пароль</h2><form id="reset-form" class="form-stack" novalidate><label class="field"><span>Код из письма</span><input id="token" value="${escapeHtml(token)}" maxlength="12" required></label>${field("Новый пароль", "password", "password", { icon: "lock", autocomplete: "new-password", minlength: 8 })}${field("Повторите пароль", "confirmPassword", "password", { icon: "lock", autocomplete: "new-password", minlength: 8 })}<button class="btn btn-primary btn-block" type="submit">Обновить пароль</button></form></section>`); }

    const nav = [{ route: "dashboard", label: "Главная", icon: "house" }, { route: "create", label: "Создать", icon: "plus" }, { route: "history", label: "История", icon: "clock-rotate-left" }, { route: "notifications", label: "События", icon: "bell" }, { route: "profile", label: "Профиль", icon: "user" }];
    function shell(content, user, route, unread = 0, title = "") {
        const activeNav = user.role === "reviewer" ? [{ route: "reviewer", label: "Проверка", icon: "user-check" }, { route: "history", label: "Списания", icon: "clipboard-check" }, { route: "notifications", label: "События", icon: "bell" }, { route: "profile", label: "Профиль", icon: "user" }] : nav;
        const links = activeNav.map((item) => `<a class="nav-link ${route === item.route ? "active" : ""}" href="#/${item.route}" ${route === item.route ? 'aria-current="page"' : ""}>${icon(item.icon)}<span>${item.label}</span>${item.route === "notifications" && unread ? `<b>${unread}</b>` : ""}</a>`).join("");
        return `<div class="app-shell"><aside class="sidebar">${logo()}<nav aria-label="Основная навигация">${links}</nav><div class="sidebar-help"><span>${icon("circle-question")}</span><div><strong>Нужна помощь?</strong><a href="#/help">Открыть справку</a></div></div><a class="user-mini" href="#/profile"><span class="avatar">${user.avatar ? `<img src="${escapeHtml(user.avatar)}" alt="">` : initials(user.name)}</span><span><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.position)}</small></span>${icon("chevron-right")}</a></aside><div class="workspace"><header class="topbar"><div><small>${escapeHtml(user.restaurant)}</small><h1>${escapeHtml(title)}</h1></div><div class="top-actions"><button class="icon-button" id="theme-quick" type="button" aria-label="Переключить тему">${icon("moon")}</button><a class="icon-button" href="#/notifications" aria-label="Уведомления">${icon("bell")}${unread ? `<span>${unread}</span>` : ""}</a></div></header><main class="page" id="main-content" tabindex="-1">${content}</main></div><nav class="mobile-nav" aria-label="Мобильная навигация">${links}</nav></div>`;
    }

    function requestCard(item) {
        const [label, statusClass] = statusMap[item.status] || statusMap.submitted;
        return `<a class="request-card" href="#/request/${escapeHtml(item.id)}"><span class="product-avatar">${item.photo ? `<img src="${escapeHtml(item.photo)}" alt="">` : item.productIcon}</span><span class="request-main"><strong>${escapeHtml(item.productName)}</strong><small>${escapeHtml(item.reason)}</small><span>${formatDate(item.createdAt)} • ${escapeHtml(item.id)}</span></span><span class="request-meta"><b>${formatNumber(item.quantity)} ${escapeHtml(item.unit)}</b><em class="status ${statusClass}">${label}</em></span>${icon("chevron-right")}</a>`;
    }
    function dashboard(user, writeoffs) {
        const today = writeoffs.filter((item) => new Date(item.createdAt).toDateString() === new Date().toDateString()).length;
        const pending = writeoffs.filter((item) => ["submitted", "review"].includes(item.status)).length;
        const approved = writeoffs.filter((item) => item.status === "approved").length;
        return `<section class="welcome"><div><span class="eyebrow">Доброе утро</span><h2>${escapeHtml(user.name.split(" ")[0])}, всё под контроле.</h2><p>Создайте заявку за минуту — AI поможет с анализом.</p></div><a class="btn btn-primary" href="#/create">${icon("camera")} Новое списание</a></section><section class="metric-grid"><article><span class="metric-icon teal">${icon("receipt")}</span><div><small>Сегодня</small><strong>${today}</strong><em>заявок</em></div></article><article><span class="metric-icon amber">${icon("clock")}</span><div><small>Ожидают</small><strong>${pending}</strong><em>проверки</em></div></article><article><span class="metric-icon green">${icon("circle-check")}</span><div><small>Принято</small><strong>${approved}</strong><em>всего</em></div></article></section><section class="dashboard-grid"><div class="panel quick-panel"><div class="panel-heading"><div><span class="eyebrow">AI assistant</span><h3>Умное списание</h3></div><span class="ai-orb">${icon("sparkles")}</span></div><ol class="quick-steps"><li><span>1</span><div><strong>Сделайте фото</strong><small>AI оценит качество и продукт</small></div></li><li><span>2</span><div><strong>Подтвердите детали</strong><small>Проверьте подсказки</small></div></li><li><span>3</span><div><strong>Отправьте</strong><small>Статус появится в истории</small></div></li></ol><a class="btn btn-secondary btn-block" href="#/create">Начать ${icon("arrow-right")}</a></div><div class="panel"><div class="panel-heading"><h3>Последние заявки</h3><a href="#/history">Все</a></div><div class="request-list">${writeoffs.slice(0, 3).map(requestCard).join("") || empty("Заявок пока нет", "Создайте первое списание.")}</div></div></section>`;
    }

    function createFlow(draft) {
        const steps = ["Фото", "AI-анализ", "Детали", "Проверка"];
        const progress = `<div class="flow-progress">${steps.map((name, i) => `<div class="${i + 1 < draft.step ? "done" : i + 1 === draft.step ? "active" : ""}"><span>${i + 1 < draft.step ? icon("check") : i + 1}</span><small>${name}</small></div>`).join("")}</div>`;
        let body;
        if (draft.step === 1) body = `<div class="capture-card"><div class="capture-visual">${icon("camera")}<span>${icon("sparkles")}</span></div><h2>Сфотографируйте продукт</h2><p>Убедитесь, что продукт целиком в кадре, а дефект хорошо виден.</p><button class="capture-zone" id="pick-photo" type="button">${icon("camera")}<strong>Сделать или выбрать фото</strong><small>JPG, PNG или WEBP до 10 МБ</small></button><input class="sr-only" id="photo-input" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"><div class="capture-tips"><span>${icon("sun")} Хороший свет</span><span>${icon("expand")} Весь продукт</span><span>${icon("hand")} Без размытия</span></div></div>`;
        else if (draft.step === 2) body = `<div class="analysis-layout"><div class="analysis-photo"><img src="${escapeHtml(draft.photo)}" alt="Загруженный продукт"><span class="scan-line"></span><div class="scan-badge">${icon("sparkles")} AI Vision</div></div><div class="analysis-status"><span class="ai-orb large">${icon("sparkles")}</span><span class="eyebrow">Анализ изображения</span><h2 id="analysis-message">Подготавливаем AI…</h2><div class="progress-track"><span id="analysis-progress"></span></div><strong id="analysis-percent">0%</strong><p>Это займёт несколько секунд.</p></div></div>`;
        else if (draft.step === 3) body = detailsForm(draft);
        else body = review(draft);
        return `<div class="flow-page"><div class="flow-header"><a class="back-link" href="#/dashboard">${icon("xmark")} Закрыть</a><div><span class="eyebrow">Новая заявка</span><h2>Списание продукции</h2></div></div>${progress}<div class="flow-content">${body}</div></div>`;
    }
    function detailsForm(draft) {
        const ai = draft.ai;
        const products = App.config.products.map((p) => `<option value="${p.id}" ${p.id === ai.productId ? "selected" : ""}>${p.icon} ${p.name}</option>`).join("");
        const reasons = App.config.reasons.map((reason) => `<option>${reason}</option>`).join("");
        return `<div class="details-layout"><aside class="ai-result"><div class="result-photo"><img src="${escapeHtml(draft.photo)}" alt="Фото заявки"><span>${ai.productIcon}</span></div><div class="confidence-ring" style="--score:${ai.confidence}"><strong>${ai.confidence}%</strong><small>уверенность</small></div><h3>${escapeHtml(ai.productName)}</h3><span class="quality good">${icon("circle-check")} Фото подходит</span><div class="ai-reason"><strong>${icon("sparkles")} Вывод AI</strong><p>${escapeHtml(ai.reasoning)}</p></div></aside><form id="details-form" class="details-form" novalidate><div class="section-heading"><span class="eyebrow">Подтвердите данные</span><h2>Что и почему списываем?</h2></div><label class="field"><span>Продукт</span><select id="productId" required>${products}</select><small class="ai-match" id="ai-match">${icon("circle-check")} AI подтверждает выбор</small></label><div class="quantity-row"><label class="field"><span>Количество</span><input id="quantity" type="number" min="0.1" max="999" step="0.1" inputmode="decimal" value="1" required></label><label class="field"><span>Единица</span><select id="unit"><option>шт</option><option>кг</option><option>л</option><option>порц.</option></select></label></div><label class="field"><span>Причина</span><select id="reason" required><option value="">Выберите причину</option>${reasons}</select></label><fieldset class="type-picker"><legend>Тип списания</legend><label><input type="radio" name="type" value="no_deduction" checked><span>${icon("building")}<strong>Без удержания</strong><small>За счёт ресторана</small></span></label><label><input type="radio" name="type" value="with_deduction"><span>${icon("user-minus")}<strong>С удержанием</strong><small>С ответственного</small></span></label></fieldset><label class="field"><span>Комментарий</span><textarea id="comment" minlength="10" maxlength="500" rows="4" required>${escapeHtml(ai.suggestedComment)}</textarea><small class="field-hint"><button type="button" id="use-ai-comment">${icon("wand-magic-sparkles")} Улучшить с AI</button><span id="comment-counter">${ai.suggestedComment.length}/500</span></small></label><div class="flow-actions"><button class="btn btn-ghost" type="button" id="retake-photo">${icon("camera-rotate")} Другое фото</button><button class="btn btn-primary" type="submit">Продолжить ${icon("arrow-right")}</button></div></form></div>`;
    }
    function review(draft) {
        const product = App.config.products.find((item) => item.id === draft.productId);
        return `<div class="review-layout"><section class="review-main"><div class="section-heading"><span class="eyebrow">Почти готово</span><h2>Проверьте заявку</h2><p>После отправки изменить её будет нельзя.</p></div><div class="review-product"><img src="${escapeHtml(draft.photo)}" alt=""><div><span class="product-avatar">${product.icon}</span><h3>${escapeHtml(product.name)}</h3><p>${formatNumber(draft.quantity)} ${escapeHtml(draft.unit)} • ${escapeHtml(draft.reason)}</p></div></div><dl class="review-list"><div><dt>Тип</dt><dd>${draft.type === "with_deduction" ? "С удержанием" : "Без удержания"}</dd></div><div><dt>Комментарий</dt><dd>${escapeHtml(draft.comment)}</dd></div></dl><button class="btn btn-ghost" id="edit-details" type="button">${icon("pen")} Изменить детали</button></section><aside class="review-ai"><span class="ai-orb">${icon("sparkles")}</span><h3>AI-проверка пройдена</h3><div class="score-row"><strong>${draft.ai.confidence}%</strong><span>уверенность</span></div><ul><li>${icon("check")} Фото чёткое</li><li>${icon("check")} Продукт совпадает</li><li>${icon("check")} Комментарий достаточен</li></ul><div class="recommendation"><span>Рекомендация</span><strong>${draft.ai.recommendation === "approve" ? "Подтвердить" : "Проверить"}</strong></div><button class="btn btn-primary btn-block" id="submit-writeoff" type="button">${icon("paper-plane")} Отправить заявку</button><small class="secure-note">${icon("shield-halved")} Данные защищены</small></aside></div>`;
    }

    function history(items, filter = "all") { const filtered = filter === "all" ? items : items.filter((item) => item.status === filter); return `<section class="section-heading page-heading"><div><span class="eyebrow">Учёт и контроль</span><h2>История списаний</h2><p>Все ваши заявки и их текущий статус.</p></div><a class="btn btn-primary" href="#/create">${icon("plus")} Новая заявка</a></section><div class="toolbar"><div class="search-box">${icon("magnifying-glass")}<input id="history-search" type="search" placeholder="Поиск по продукту или ID"></div><div class="filter-pills">${[["all", "Все"], ["submitted", "Отправлены"], ["review", "На проверке"], ["approved", "Приняты"], ["rejected", "Отклонены"]].map(([id, label]) => `<button class="${filter === id ? "active" : ""}" data-history-filter="${id}" type="button">${label}</button>`).join("")}</div></div><div class="panel history-panel"><div class="request-list" id="history-results">${filtered.map(requestCard).join("") || empty("Ничего не найдено", "Измените фильтр или создайте заявку.")}</div></div>`; }
    function detail(item) {
        if (!item) return empty("Заявка не найдена", "Возможно, она была удалена.", "#/history");
        const [label, statusClass] = statusMap[item.status] || statusMap.submitted;
        const photo = item.photo ? `<img src="${escapeHtml(item.photo)}" alt="Фото списываемого продукта">` : `<span>${escapeHtml(item.productIcon || "📦")}</span>`;
        const timeline = (item.timeline || []).map((event) => `<li><span></span><div><strong>${escapeHtml((statusMap[event.status] || [event.status])[0])}</strong><small>${formatDate(event.at, true)}</small></div></li>`).join("");
        return `<a class="back-link" href="#/history">${icon("arrow-left")} К истории</a><div class="detail-grid"><section class="panel detail-main"><div class="detail-header"><div><span class="eyebrow">${escapeHtml(item.id)}</span><h2>${escapeHtml(item.productName)}</h2><p>Создано ${formatDate(item.createdAt, true)}</p></div><em class="status ${statusClass}">${label}</em></div><div class="detail-photo ${item.photo ? "has-photo" : ""}">${photo}</div><dl class="detail-list"><div><dt>Количество</dt><dd>${formatNumber(item.quantity)} ${escapeHtml(item.unit)}</dd></div><div><dt>Причина</dt><dd>${escapeHtml(item.reason)}</dd></div><div><dt>Тип</dt><dd>${item.type === "with_deduction" ? "С удержанием" : "Без удержания"}</dd></div><div><dt>Комментарий</dt><dd>${escapeHtml(item.comment)}</dd></div></dl></section><aside class="detail-side"><section class="panel"><div class="panel-heading"><h3>История статуса</h3></div><ol class="timeline">${timeline}</ol></section>${item.ai ? `<section class="panel ai-summary"><span class="ai-orb">${icon("sparkles")}</span><div><span class="eyebrow">AI-анализ</span><h3>${escapeHtml(item.ai.condition)}</h3><p>${escapeHtml(item.ai.reasoning)}</p><strong>${item.ai.confidence}% уверенности</strong></div></section>` : ""}</aside></div>`;
    }
    function notifications(items) {
        const content = items.map((item) => `<article class="notification-item ${item.read ? "" : "unread"}"><span>${icon(item.read ? "envelope-open" : "bell")}</span><div><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.body)}</p><small>${formatDate(item.createdAt, true)}</small></div></article>`).join("");
        return `<section class="section-heading page-heading"><div><span class="eyebrow">Обновления</span><h2>Уведомления</h2></div><button class="btn btn-ghost" id="read-all" type="button">Прочитать все</button></section><div class="panel notification-list">${content || empty("Уведомлений нет", "Здесь появятся изменения статусов.")}</div>`;
    }
    function settings(user) {
        const current = user.settings || {};
        return `<section class="section-heading page-heading"><div><span class="eyebrow">Персонализация</span><h2>Настройки</h2></div></section><div class="settings-stack"><section class="panel settings-group"><label><span>${icon("moon")}<strong>Тёмная тема</strong></span><input type="checkbox" data-setting="darkMode" ${current.darkMode ? "checked" : ""}></label><label><span>${icon("bell")}<strong>Уведомления</strong></span><input type="checkbox" data-setting="notifications" ${current.notifications ? "checked" : ""}></label><label><span>${icon("mobile-screen")}<strong>Вибрация</strong></span><input type="checkbox" data-setting="haptics" ${current.haptics ? "checked" : ""}></label></section><button class="btn btn-danger" id="logout" type="button">${icon("right-from-bracket")} Выйти</button></div>`;
    }
    function help() { return `<div class="help-grid"><div class="panel"><span class="auth-icon">${icon("circle-question")}</span><h2>Нужна помощь?</h2><p>Обратитесь к проверяющему смены или в службу поддержки.</p></div><a class="btn btn-secondary" href="mailto:support@b-scan.kz">Написать в поддержку</a></div>`; }
    function about() { return `<div class="about-card"><span class="brand-mark brand-mark-large">${icon("sparkles")}</span><h2>B-scan</h2><p class="version">Version ${App.config.version}</p><p>Интеллектуальное рабочее место для учёта списаний в ресторанах.</p><div class="about-values"><span>${icon("shield-halved")} Безопасно</span><span>${icon("universal-access")} Доступно</span><span>${icon("leaf")} Ответственно</span></div><small>© 2026 B-scan. Все права защищены.</small></div>`; }
    function empty(title, body, href = "") { return `<div class="empty-state"><span>${icon("box-open")}</span><h3>${title}</h3><p>${body}</p>${href ? `<a class="btn btn-secondary" href="${href}">Вернуться</a>` : ""}</div>`; }
    function success(item) { return `<div class="success-screen"><div class="success-check">${icon("check")}</div><span class="eyebrow">Готово</span><h2>Заявка отправлена</h2><p>Мы сообщим, когда проверяющий её проверит.</p><div class="success-id"><span>ID заявки</span><strong>${escapeHtml(item.id)}</strong></div><div class="success-actions"><a class="btn btn-primary" href="#/request/${item.id}">Открыть заявку</a><a class="btn btn-ghost" href="#/dashboard">На главную</a></div></div>`; }

    function onboarding(draft) {
        const reviewerFlow = draft.role === "reviewer";
        const stepNames = ["Личные данные", "Роль", "Точка", "Документ", "Проверка"];
        const displayStep = draft.step;
        const steps = `<div class="onboarding-steps">${stepNames.map((name, index) => `<div class="${displayStep > index + 1 ? "done" : displayStep === index + 1 ? "active" : ""}"><span>${displayStep > index + 1 ? icon("check") : index + 1}</span><small>${name}</small></div>`).join("")}</div>`;
        let content = "";
        if (draft.step === 1) content = `<form id="onboarding-personal" class="onboarding-form form-grid" novalidate><div class="section-heading form-span"><span class="eyebrow">Шаг 1 из 5</span><h2>Расскажите о себе</h2><p>Вводите данные точно как в удостоверении личности.</p></div>${onboardingInput("Фамилия", "lastName", "text", draft.lastName, "family-name")}${onboardingInput("Имя", "firstName", "text", draft.firstName, "given-name")}${onboardingInput("Отчество", "patronymic", "text", draft.patronymic, "additional-name")}<label class="field"><span>Дата рождения</span><input id="birthDate" type="date" value="${escapeHtml(draft.birthDate)}" max="${new Date().toISOString().slice(0, 10)}" required><small class="age-output" id="age-output">${draft.age ? `Возраст: ${draft.age}` : "Возраст рассчитается автоматически"}</small></label>${onboardingInput("Телефон", "phone", "tel", draft.phone, "tel", "+7 700 000 00 00")}${onboardingInput("Email", "email", "email", draft.email, "email", "name@example.com")}${onboardingInput("Пароль", "password", "password", draft.password, "new-password", "Минимум 8 символов")}${onboardingInput("Повторите пароль", "confirmPassword", "password", draft.confirmPassword, "new-password")}<div class="onboarding-actions form-span"><a class="btn btn-ghost" href="#/login">Отмена</a><button class="btn btn-primary" type="submit">Продолжить ${icon("arrow-right")}</button></div></form>`;
        if (draft.step === 2) content = `<form id="onboarding-role" class="onboarding-form"><div class="section-heading"><span class="eyebrow">Шаг 2</span><h2>Выберите вашу роль</h2><p>От роли зависит набор доступных функций.</p></div><div class="role-cards"><label><input type="radio" name="onboardingRole" value="sender" ${draft.role !== "reviewer" ? "checked" : ""}><span>${icon("paper-plane")}<strong>Отправитель</strong><small>Создаёт и отслеживает заявки на списание</small><em>${icon("check")} Работа на точке</em></span></label><label><input type="radio" name="onboardingRole" value="reviewer" ${draft.role === "reviewer" ? "checked" : ""}><span>${icon("user-check")}<strong>Проверяющий</strong><small>Проверяет отправителей и заявки</small><em>${icon("shield-halved")} Расширенный доступ</em></span></label></div><div class="manager-onboarding-secret ${reviewerFlow ? "visible" : ""}" id="manager-onboarding-secret"><label class="field"><span>Секретный код проверяющего</span><div class="input-wrap">${icon("key")}<input id="managerSecretCode" type="password" value="${escapeHtml(draft.managerSecretCode || "")}" placeholder="Введите код проверяющего" autocomplete="off"></div><small>Код проверяется вместе с личным паролем.</small></label></div>${onboardingActions()}</form>`;
        if (draft.step === 3) content = `<form id="onboarding-location" class="onboarding-form"><div class="section-heading"><span class="eyebrow">Шаг 3 из 5</span><h2>Выберите точку Bahandi</h2><p>Точка будет привязана к аккаунту после одобрения.</p></div><div class="location-map"><span class="map-pin pin-a">${icon("location-dot")}</span><span class="map-pin pin-b">${icon("location-dot")}</span><span class="map-pin pin-c">${icon("location-dot")}</span><div><strong>Bahandi Locations</strong><small>6 точек в 3 городах</small></div></div><div class="location-cards">${App.config.locations.map((location) => `<label><input type="radio" name="locationId" value="${location.id}" ${draft.locationId === location.id ? "checked" : ""} required><span><i>${icon("store")}</i><strong>${escapeHtml(location.name)}</strong><small>${escapeHtml(location.city)} • ${escapeHtml(location.address)}</small><em>${icon("clock")} ${location.hours}</em></span></label>`).join("")}</div>${onboardingActions()}</form>`;
        if (draft.step === 4) content = `<div class="onboarding-form"><div class="section-heading"><span class="eyebrow">Шаг 4 из 5</span><h2>Подтвердите личность</h2><p>Загрузите чёткое фото удостоверения. Документ получит только проверяющий.</p></div><button class="identity-upload ${draft.idDocument ? "has-preview" : ""}" id="pick-identity" type="button">${draft.idDocument ? `<img src="${escapeHtml(draft.idDocument)}" alt="Превью удостоверения"><span>${icon("camera-rotate")} Заменить фото</span>` : `${icon("id-card")}<strong>Сфотографировать или загрузить</strong><small>JPG, PNG или WEBP до 10 МБ</small>`}</button><input class="sr-only" id="identity-input" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"><div class="privacy-note">${icon("lock")}<span><strong>Данные защищены</strong><small>Изображение используется только для одобрения аккаунта.</small></span></div>${onboardingActions(!draft.idDocument)}</div>`;
        if (draft.step === 5) { const location = App.config.locations.find((item) => item.id === draft.locationId); content = `<div class="onboarding-form"><div class="section-heading"><span class="eyebrow">Шаг 5 из 5</span><h2>Проверьте заявку</h2><p>После отправки аккаунт будет ожидать одобрения.</p></div><div class="onboarding-review"><img src="${escapeHtml(draft.idDocument)}" alt="Удостоверение"><dl><div><dt>ФИО</dt><dd>${escapeHtml(`${draft.lastName} ${draft.firstName} ${draft.patronymic}`)}</dd></div><div><dt>Возраст</dt><dd>${draft.age}</dd></div><div><dt>Контакты</dt><dd>${escapeHtml(draft.phone)}<br>${escapeHtml(draft.email)}</dd></div><div><dt>Роль</dt><dd>${reviewerFlow ? "Проверяющий" : "Отправитель"}</dd></div><div><dt>Точка</dt><dd>${escapeHtml(location?.name)}</dd></div></dl></div><label class="check consent"><input id="onboarding-consent" type="checkbox" required><span>Подтверждаю достоверность данных и согласие на их обработку</span></label><div class="onboarding-actions"><button class="btn btn-ghost" id="onboarding-back" type="button">${icon("arrow-left")} Назад</button><button class="btn btn-primary" id="submit-onboarding" type="button">${icon("paper-plane")} Отправить заявку</button></div></div>`; }
        return authLayout(`<section class="onboarding-card"><a class="back-link" href="#/login">${icon("xmark")} Закрыть</a>${steps}${content}</section>`, "Команда Bahandi начинается здесь.");
    }

    function onboardingInput(label, id, type, value = "", autocomplete = "", placeholder = "") { return `<label class="field"><span>${label}</span><input id="${id}" type="${type}" value="${escapeHtml(value)}" autocomplete="${autocomplete}" placeholder="${placeholder}" required></label>`; }
    function onboardingActions(disabled = false) { return `<div class="onboarding-actions"><button class="btn btn-ghost" id="onboarding-back" type="button">${icon("arrow-left")} Назад</button><button class="btn btn-primary" id="onboarding-next" type="button" ${disabled ? "disabled" : ""}>Продолжить ${icon("arrow-right")}</button></div>`; }

    function pending(application) {
        const rejected = application?.status === "rejected";
        return authLayout(`<section class="pending-card"><div class="pending-animation ${rejected ? "rejected" : ""}">${icon(rejected ? "xmark" : "hourglass-half")}</div><span class="eyebrow">${rejected ? "Требуется исправление" : "Заявка принята"}</span><h2>${rejected ? "Ваша регистрация отклонена" : "Ваша регистрация успешно отправлена"}</h2><p>${rejected ? "Исправьте данные и отправьте новую заявку." : "Ваш аккаунт сейчас на проверке. Доступ появится после одобрения проверяющим."}</p><div class="application-status"><span>Статус</span><strong>${rejected ? "🔴 Отклонена" : "🟡 Ожидает одобрения"}</strong>${application ? `<small>${escapeHtml(application.registrationId || application.email)} • ${formatDate(application.createdAt, true)}</small>` : ""}</div>${rejected ? `<div class="rejection-box"><strong>Причина</strong><p>${escapeHtml(application.rejectionReason)}</p></div><a class="btn btn-primary btn-block" href="#/register">Отправить новую заявку</a>` : `<button class="btn btn-secondary btn-block" id="refresh-approval" type="button">${icon("rotate")} Обновить статус</button>`}<a class="pending-login" href="#/login">Вернуться ко входу</a></section>`);
    }

    function reviewer(applications, writeoffs) {
        const pendingWriteoffs = writeoffs.filter((item) => ["submitted", "review"].includes(item.status));
        const registrations = applications.map((user) => `<article class="approval-card" data-user-id="${user.id}"><img src="${escapeHtml(user.idDocument)}" alt="Документ ${escapeHtml(user.name)}"><div><span class="eyebrow">${user.role === "reviewer" ? "Проверяющий" : "Отправитель"}</span><h4>${escapeHtml(`${user.lastName} ${user.firstName} ${user.patronymic}`)}</h4><p>${escapeHtml(user.restaurant)} • ${user.age} лет</p><small>${escapeHtml(user.email)}<br>${escapeHtml(user.phone)}</small></div><div class="approval-actions"><button class="btn btn-primary" data-approve-user="${user.id}" type="button">${icon("check")} Одобрить</button><button class="btn btn-ghost" data-reject-user="${user.id}" type="button">${icon("xmark")} Отклонить</button></div></article>`).join("");
        const requests = pendingWriteoffs.map((item) => `<article class="trust-request"><div><span class="product-avatar">${item.productIcon}</span><div><strong>${escapeHtml(item.productName)}</strong><small>${formatNumber(item.quantity)} ${escapeHtml(item.unit)} • ${escapeHtml(item.id)}</small></div></div><div class="trust-signal"><span>Trust Score</span><strong>${item.employeeTrust}/100</strong><small>${item.employeeTrust >= 90 ? "Высокая уверенность на основе истории" : "Требуется ручная проверка"}</small></div><div class="approval-actions"><a class="btn btn-ghost" href="#/request/${item.id}">Детали</a><button class="btn btn-primary" data-approve-writeoff="${item.id}" data-owner="${item.userId}" type="button">Одобрить</button><button class="btn btn-ghost" data-reject-writeoff="${item.id}" data-owner="${item.userId}" type="button">Отклонить</button></div></article>`).join("");
        return `<section class="section-heading page-heading"><div><span class="eyebrow">Рабочее место проверяющего</span><h2>Центр одобрения</h2><p>Проверяйте новых отправителей и заявки.</p></div><span class="reviewer-badge">${icon("shield-halved")} Защищённый доступ</span></section><div class="reviewer-stats"><article><strong>${applications.length}</strong><span>Новых аккаунтов</span></article><article><strong>${pendingWriteoffs.length}</strong><span>Списаний на проверке</span></article><article><strong>${applications.filter((item) => item.role === "reviewer").length}</strong><span>Заявок reviewer</span></article></div><div class="reviewer-stack"><section class="panel"><div class="panel-heading"><h3>Заявки на регистрацию</h3></div><div class="approval-list">${registrations || empty("Новых заявок нет", "Все аккаунты обработаны.")}</div></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">AI Trust Intelligence</span><h3>Списания на проверке</h3></div><span class="ai-orb">${icon("sparkles")}</span></div><div class="trust-request-list">${requests || empty("Все списания проверены", "Новые заявки появятся здесь.")}</div></section></div>`;
    }

    function employeePass(user, score) {
        return `<a class="back-link" href="#/profile">${icon("arrow-left")} К профилю</a><div class="pass-page"><section class="employee-pass"><div class="pass-glow"></div><header>${logo()}<span>B-SCAN PASS</span></header><div class="pass-person"><div class="avatar large">${user.avatar ? `<img src="${escapeHtml(user.avatar)}" alt="">` : initials(user.name)}</div><div><span>${user.role === "reviewer" ? "Проверяющий" : "Отправитель"}</span><h2>${escapeHtml(`${user.lastName} ${user.firstName}`)}</h2><p>${escapeHtml(user.patronymic)}</p></div></div><dl><div><dt>B-scan ID</dt><dd>${escapeHtml(user.employeeId)}</dd></div><div><dt>Точка</dt><dd>${escapeHtml(user.restaurant)}</dd></div><div><dt>В команде с</dt><dd>${formatDate(user.joinedAt)}</dd></div><div><dt>Статус</dt><dd><span class="pass-active">Активен</span></dd></div></dl><div class="pass-qr" id="employee-qr" data-qr="${escapeHtml(`bscan://employee/${user.employeeId}?token=${user.passToken}`)}"></div><footer><span>Trust Score</span><strong>${score}/100</strong><small>Покажите QR-код для проверки</small></footer></section><aside class="pass-help"><h3>Цифровой пропуск</h3><p>QR-код уникально идентифицирует отправителя. Не пересылайте его другим людям.</p><button class="btn btn-secondary btn-block" id="print-pass" type="button">${icon("print")} Напечатать</button></aside></div>`;
    }

    function employeeProfile(user, score, achievements) {
        return `<div class="profile-hero panel"><div class="avatar large">${user.avatar ? `<img src="${escapeHtml(user.avatar)}" alt="">` : initials(user.name)}</div><div><span class="eyebrow">${escapeHtml(user.employeeId)}</span><h2>${escapeHtml(`${user.lastName} ${user.firstName} ${user.patronymic}`)}</h2><p>${escapeHtml(user.position)} • ${escapeHtml(user.restaurant)}</p></div><a class="btn btn-primary" href="#/pass">${icon("qrcode")} B-scan Pass</a></div><div class="profile-dashboard"><section class="panel trust-score"><div class="score-gauge" style="--score:${score}"><strong>${score}</strong><span>/ 100</span></div><div><span class="eyebrow">Рейтинг доверия отправителя</span><h3>${score >= 90 ? "Очень надёжный отправитель" : score >= 75 ? "Надёжный отправитель" : "Требует внимания"}</h3><p>Счёт формируется по точности, истории и последовательности заявок.</p></div></section><section class="panel achievements"><div class="panel-heading"><h3>Достижения</h3><span>${achievements.filter((item) => item.unlocked).length}/${achievements.length}</span></div><div>${achievements.map((item) => `<article class="${item.unlocked ? "unlocked" : "locked"}"><span>${item.icon}</span><strong>${escapeHtml(item.name)}</strong>${item.unlocked ? icon("circle-check") : icon("lock")}</article>`).join("")}</div></section><form class="panel profile-form" id="profile-form"><div class="section-heading"><span class="eyebrow">Личные данные</span><h2>Профиль</h2></div><div class="form-grid"><label class="field"><span>Фамилия</span><input value="${escapeHtml(user.lastName)}" disabled></label><label class="field"><span>Имя</span><input value="${escapeHtml(user.firstName)}" disabled></label><label class="field"><span>Отчество</span><input value="${escapeHtml(user.patronymic)}" disabled></label><label class="field"><span>B-scan ID</span><input value="${escapeHtml(user.employeeId)}" disabled></label><label class="field"><span>Телефон</span><input id="phone" type="tel" value="${escapeHtml(user.phone)}"></label><label class="field"><span>Email</span><input value="${escapeHtml(user.email)}" disabled></label><label class="field"><span>Дата приёма</span><input value="${formatDate(user.joinedAt)}" disabled></label><label class="field"><span>Статус</span><input value="Активен" disabled></label></div><div class="profile-form-actions"><label class="btn btn-ghost avatar-upload">${icon("camera")} Фото<input class="sr-only" id="avatar-input" type="file" accept="image/jpeg,image/png,image/webp"></label><button class="btn btn-primary" type="submit">Сохранить</button><a class="btn btn-ghost" href="#/settings">${icon("gear")} Настройки</a></div></form></div>`;
    }

    App.views = { login, register: onboarding, pending, reviewer, forgot, reset, shell, dashboard, createFlow, history, detail, notifications, profile: employeeProfile, employeePass, settings, help, about, success, requestCard, empty };
})(window);
